### ISSUE TITLE
Don't attempt to submit a settlement for 0

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/settlement-xrp#17]
If the amount is going to be 0, the settlement engine shouldn't try submitting it to rippled

**Comment by kincaidoneil** [comment]
Settlement core had a check for that [here](https://github.com/interledgerjs/settlement-core/blob/995b62489d163bebf54cdbf18765daf7229b9fcf/src/index.ts#L279), but it's possible if the connector has a smaller scale since it rounds the amount down.
