### ISSUE TITLE
Update the `/settlements` controller to return a `SettlementResponse`

### ISSUE THREAD

**Issue by sappenin** [interledgerjs/settlement-xrp#7]
When an API client makes a request to `/accounts/:id/settlements`, the controller should return a JSON object with the amount committed to be settled, and the Settlement Engine's scale, like this:

```json
{
  "amount": "1000",
  "scale": "6"
}
```

**Comment by gakonst** [comment]
Rust connector implements this in https://github.com/emschwartz/interledger-rs/pull/199
